version: '3.8'

services:
  nginx:
    build: .
    container_name: sni_proxy
    volumes:
      - ./logs:/var/log/nginx
    ports:
      - "443:443"
    restart: unless-stopped
    ulimits:
      nofile:
        soft: 65535
        hard: 65535